"""v5.66 — zombie derived-memory prune fix.

Root cause: prune passes 2, 3, 5, 6 used `access_count != 0` as an immortality
guard — any memory ever accessed was spared FOREVER regardless of age.  recall()
bumps access_count, so once a derived memory surfaced once it became a zombie.

Fix: replace "ever-accessed = immortal" with "recently-accessed = spare".
Purge when: created_at < cutoff AND last_accessed < cutoff (old AND not recently
accessed).  Recency window = same max_age cutoff as the creation gate.

TDD: RED tests written against pre-fix code, GREEN after fix.
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from unittest.mock import MagicMock, patch

from yadgar._shared.curation.prune_passes import _memify_prune

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _settings(
    cold_threshold=0.05,
    auto_generated_max_age=30,
    auto_abstracted_max_age=30,
    dream_max_age=14,
    action_stream_max_age=90,
):
    s = MagicMock()
    s.COLD_THRESHOLD = cold_threshold
    s.AUTO_GENERATED_MEMORY_MAX_AGE_DAYS = auto_generated_max_age
    s.AUTO_ABSTRACTED_MEMORY_MAX_AGE_DAYS = auto_abstracted_max_age
    s.DREAM_INSIGHT_MAX_AGE_DAYS = dream_max_age
    s.ACTION_STREAM_MAX_AGE_DAYS = action_stream_max_age
    return s


def _mem(
    mid,
    tags,
    heat=0.5,
    access_count=0,
    is_protected=False,
    created_days_ago=0,
    last_accessed_days_ago=None,  # default: mirrors created_at
    content="memory content",
    **kw,
):
    """Build a minimal memory dict with explicit last_accessed support.  Extra fields via **kw."""
    created = (datetime.now(UTC) - timedelta(days=created_days_ago)).isoformat()
    if last_accessed_days_ago is None:
        last_accessed = created  # never recalled after creation
    else:
        last_accessed = (datetime.now(UTC) - timedelta(days=last_accessed_days_ago)).isoformat()
    return {
        "id": mid,
        "tags": tags,
        "heat": heat,
        "confidence": kw.get("confidence", 1.0),
        "access_count": access_count,
        "is_protected": is_protected,
        "created_at": created,
        "last_accessed": last_accessed,
        "content": content,
    }


def _storage(*memories):
    s = MagicMock()
    s.get_memories_by_heat.return_value = list(memories)
    return s


# ---------------------------------------------------------------------------
# Pass 2 (auto-generated): recency-gated immortality fix
# ---------------------------------------------------------------------------


class TestPass2AutoGeneratedRecency:
    def test_old_stale_accessed_is_purged(self):
        """OLD + NOT recently accessed + access_count>0 -> PURGED.

        PRE-FIX (RED): access_count=2 triggers `continue` -> not purged -> FAIL.
        POST-FIX (GREEN): last_accessed old -> eligible -> purged -> PASS.
        """
        mem = _mem(
            200,
            ["auto-generated"],
            heat=0.01,
            access_count=2,
            created_days_ago=60,
            last_accessed_days_ago=45,  # stale: 45d ago, cutoff=30d
        )
        storage = _storage(mem)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(cold_threshold=0.05, auto_generated_max_age=30), stats)
        storage.delete_memory.assert_called_once_with(200)
        assert stats["pruned"] == 1

    def test_old_recently_accessed_is_spared(self):
        """OLD + recently accessed (within cutoff) + access_count>0 -> SPARED."""
        mem = _mem(
            201,
            ["auto-generated"],
            heat=0.01,
            access_count=3,
            created_days_ago=60,
            last_accessed_days_ago=5,  # recent: 5d ago, cutoff=30d -> spare
        )
        storage = _storage(mem)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(cold_threshold=0.05, auto_generated_max_age=30), stats)
        storage.delete_memory.assert_not_called()

    def test_protected_always_spared(self):
        """is_protected=True -> always spared regardless of recency."""
        mem = _mem(
            202,
            ["auto-generated"],
            heat=0.01,
            access_count=5,
            is_protected=True,
            created_days_ago=60,
            last_accessed_days_ago=45,
        )
        storage = _storage(mem)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(cold_threshold=0.05, auto_generated_max_age=30), stats)
        storage.delete_memory.assert_not_called()

    def test_zero_access_count_old_still_purged(self):
        """access_count=0 old -> still purged (existing behavior preserved)."""
        mem = _mem(
            203,
            ["auto-generated"],
            heat=0.01,
            access_count=0,
            created_days_ago=60,
            last_accessed_days_ago=60,
        )
        storage = _storage(mem)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(cold_threshold=0.05, auto_generated_max_age=30), stats)
        storage.delete_memory.assert_called_once_with(203)


# ---------------------------------------------------------------------------
# Pass 3 (auto-abstracted): PRIMARY zombie fix — memory:1110 scenario
# ---------------------------------------------------------------------------


class TestPass3AutoAbstractedRecency:
    def test_memory_1110_scenario_purged(self):
        """Reproduces memory:1110: 38d old, last_accessed 32d ago, access_count=2.

        PRE-FIX (RED): access_count=2 -> `continue` -> immortal zombie -> FAIL.
        POST-FIX (GREEN): last_accessed 32d ago > 30d cutoff -> purged -> PASS.
        """
        mem = _mem(
            1110,
            ["semantic", "auto-abstracted"],
            heat=0.0,
            access_count=2,
            created_days_ago=38,
            last_accessed_days_ago=32,  # 32d ago, cutoff=30d -> stale
        )
        storage = _storage(mem)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(auto_abstracted_max_age=30), stats)
        storage.delete_memory.assert_called_once_with(1110)
        assert stats["pruned"] == 1

    def test_old_accessed_recently_spared(self):
        """Old auto-abstracted but accessed 3d ago -> spared (still useful)."""
        mem = _mem(
            1111,
            ["auto-abstracted"],
            heat=0.3,
            access_count=5,
            created_days_ago=38,
            last_accessed_days_ago=3,  # recent: 3d ago, cutoff=30d -> spare
        )
        storage = _storage(mem)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(auto_abstracted_max_age=30), stats)
        storage.delete_memory.assert_not_called()

    def test_protected_auto_abstracted_always_spared(self):
        """Protected auto-abstracted: always spared even if old+stale."""
        mem = _mem(
            1112,
            ["auto-abstracted"],
            heat=0.0,
            access_count=2,
            is_protected=True,
            created_days_ago=38,
            last_accessed_days_ago=35,
        )
        storage = _storage(mem)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(auto_abstracted_max_age=30), stats)
        storage.delete_memory.assert_not_called()

    def test_anchor_tag_protected_spared(self):
        """_anchor tagged memory: is_protected=True -> always spared."""
        mem = _mem(
            1113,
            ["auto-abstracted", "_anchor"],
            heat=0.0,
            access_count=10,
            is_protected=True,
            created_days_ago=100,
            last_accessed_days_ago=90,
        )
        storage = _storage(mem)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(auto_abstracted_max_age=30), stats)
        storage.delete_memory.assert_not_called()

    def test_unaccessed_old_still_purged(self):
        """access_count=0, old, last_accessed=created_at -> still purged."""
        mem = _mem(
            1114,
            ["auto-abstracted"],
            heat=0.0,
            access_count=0,
            created_days_ago=45,
            last_accessed_days_ago=45,
        )
        storage = _storage(mem)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(auto_abstracted_max_age=30), stats)
        storage.delete_memory.assert_called_once_with(1114)


# ---------------------------------------------------------------------------
# Pass 5 (action-stream age cap): same immortality bug
# ---------------------------------------------------------------------------


class TestPass5ActionStreamRecency:
    def test_old_stale_accessed_is_purged(self):
        """OLD action-stream + not recently accessed + access_count>0 -> PURGED.

        PRE-FIX (RED): access_count=1 -> `continue` -> spared -> FAIL.
        POST-FIX (GREEN): last_accessed old -> eligible -> purged -> PASS.
        """
        mem = _mem(
            500,
            ["_action_stream"],
            heat=0.4,
            confidence=0.9,
            access_count=1,
            created_days_ago=180,
            last_accessed_days_ago=120,  # stale: 120d ago, cutoff=90d -> purge
        )
        storage = _storage(mem)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(action_stream_max_age=90, cold_threshold=0.05), stats)
        storage.delete_memory.assert_called_once_with(500)

    def test_old_recently_accessed_spared(self):
        """OLD action-stream but accessed 10d ago -> spared."""
        mem = _mem(
            501,
            ["_action_stream"],
            heat=0.4,
            confidence=0.9,
            access_count=3,
            created_days_ago=180,
            last_accessed_days_ago=10,  # recent: 10d ago, cutoff=90d -> spare
        )
        storage = _storage(mem)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(action_stream_max_age=90, cold_threshold=0.05), stats)
        storage.delete_memory.assert_not_called()


# ---------------------------------------------------------------------------
# Pass 6 (degenerate): drop access_count guard entirely (never meaningful)
# ---------------------------------------------------------------------------


class TestPass6DegenerateRecency:
    def test_degenerate_accessed_is_purged(self):
        """Degenerate auto-abstracted + access_count>0 -> PURGED.

        PRE-FIX (RED): access_count=2 -> `continue` -> spared -> FAIL.
        POST-FIX (GREEN): degenerate = never meaningful -> purged -> PASS.

        Rationale: degenerate content was never valid signal; protecting it
        because someone accidentally triggered a recall is wrong.
        """
        mem = _mem(
            600,
            ["auto-abstracted"],
            access_count=2,
            content="Recurring pattern across 3 observations: frequently modified together",
        )
        storage = _storage(mem)
        stats = {"pruned": 0}

        with patch(
            "yadgar._shared.curation.prune_passes._is_degenerate_auto_abstracted",
            return_value=True,
        ):
            _memify_prune(storage, _settings(), stats)

        storage.delete_memory.assert_called_once_with(600)
        assert stats["pruned"] == 1

    def test_degenerate_protected_still_spared(self):
        """is_protected always wins even for degenerate content."""
        mem = _mem(
            601,
            ["auto-abstracted"],
            access_count=2,
            is_protected=True,
            content="Recurring pattern across 3 observations: frequently modified together",
        )
        storage = _storage(mem)
        stats = {"pruned": 0}

        with patch(
            "yadgar._shared.curation.prune_passes._is_degenerate_auto_abstracted",
            return_value=True,
        ):
            _memify_prune(storage, _settings(), stats)

        storage.delete_memory.assert_not_called()

    def test_non_degenerate_accessed_spared(self):
        """Non-degenerate content: not purged regardless of access_count."""
        mem = _mem(
            602,
            ["auto-abstracted"],
            access_count=5,
            content="Real semantic cluster content",
        )
        storage = _storage(mem)
        stats = {"pruned": 0}

        with patch(
            "yadgar._shared.curation.prune_passes._is_degenerate_auto_abstracted",
            return_value=False,
        ):
            _memify_prune(storage, _settings(), stats)

        storage.delete_memory.assert_not_called()
