"""Back-compat shim — metrics moved into ``yadgar._shared.observability`` (T2 Car D1, no-lone-files law ADR-0084).

PEP-562 shim (Car 0 #167 precedent): symbol imports from the old path keep
working. Lazy importlib forward — the target only loads on first attribute
access. New code must import from ``yadgar._shared.observability.metrics`` instead.
"""

from typing import Final

_TARGET: Final = "yadgar._shared.observability.metrics"
_EXPORTS: Final = (
    "CONTENT_TYPE_LATEST",
    "CollectorRegistry",
    "Counter",
    "Gauge",
    "Histogram",
    "Request",
    "Response",
    "TYPE_CHECKING",
    "_CB_STATE_VALUES",
    "_collect_data_quality",
    "_collect_pool_stats",
    "_collect_process_metrics",
    "_collect_queue_depths",
    "_dq_count",
    "_dq_set_embedding_gauges",
    "_dq_set_surprise_gauges",
    "_is_metrics_enabled",
    "_loop_lag_probe",
    "_parse_surprise_scores",
    "_record_loop_lag",
    "_registry",
    "annotations",
    "generate_latest",
    "hook_record_failure",
    "loop_heartbeat",
    "loop_record_exception",
    "metrics_handler",
    "record_cache_evict",
    "record_cache_hit",
    "record_cache_miss",
    "resolve_knob",
    "set_cache_size",
    "start_loop_lag_monitor",
    "stop_loop_lag_monitor",
    "time",
    "yadgar_action_batch_size",
    "yadgar_archive_purged_total",
    "yadgar_archive_retention_skipped_total",
    "yadgar_astrocyte_assign_duration_ms",
    "yadgar_backend_reachable",
    "yadgar_cache_evictions_total",
    "yadgar_cache_hit_total",
    "yadgar_cache_miss_total",
    "yadgar_cache_size_entries",
    "yadgar_circuit_breaker_state",
    "yadgar_cold_purge_candidates",
    "yadgar_config_value",
    "yadgar_consolidation_duration_seconds",
    "yadgar_curator_duration_ms",
    "yadgar_curator_merge_outcome",
    "yadgar_data_quality_domain_coverage",
    "yadgar_data_quality_duplicate_rate",
    "yadgar_data_quality_embedding_valid_ratio",
    "yadgar_data_quality_null_embedding_count",
    "yadgar_data_quality_surprise_p50",
    "yadgar_data_quality_surprise_p95",
    "yadgar_data_quality_zombie_rate",
    "yadgar_dlq_rejection_count",
    "yadgar_dlq_size",
    "yadgar_drain_cycle_duration_ms",
    "yadgar_drain_stage_ms",
    "yadgar_drainer_lag_ms",
    "yadgar_embedding_cache_hits_total",
    "yadgar_embedding_cache_misses_total",
    "yadgar_encode_duration_ms",
    "yadgar_encode_queue_depth",
    "yadgar_engram_allocate_duration_ms",
    "yadgar_entity_extract_duration_ms",
    "yadgar_event_loop_lag_max_seconds",
    "yadgar_event_loop_lag_seconds",
    "yadgar_exception_total",
    "yadgar_graph_api_orphan_edges_dropped_total",
    "yadgar_hook_execution_duration_ms",
    "yadgar_hook_failure_total",
    "yadgar_hook_recall_timeout_total",
    "yadgar_llm_call_duration_ms",
    "yadgar_llm_decision",
    "yadgar_log_dropped_total",
    "yadgar_log_file_rotations_total",
    "yadgar_log_file_size_bytes",
    "yadgar_loop_errors_total",
    "yadgar_loop_last_run_unix_timestamp",
    "yadgar_mcp_auth_check_duration_ms",
    "yadgar_mcp_request_count",
    "yadgar_mcp_request_duration_ms",
    "yadgar_process_cpu_percent",
    "yadgar_process_open_fds",
    "yadgar_process_rss_bytes",
    "yadgar_python_gc_duration_ms",
    "yadgar_queue_depth",
    "yadgar_recall_duration_ms",
    "yadgar_recall_profile_invocations_total",
    "yadgar_recall_result_count",
    "yadgar_recall_stage_candidates_in",
    "yadgar_recall_stage_candidates_out",
    "yadgar_recall_stage_duration_seconds",
    "yadgar_recall_stage_ms",
    "yadgar_requests_total",
    "yadgar_signals_payload_oversized_total",
    "yadgar_subagent_capture_rate",
    "yadgar_subagent_dispatch_count",
    "yadgar_surrealdb_connection_pool_wait_ms",
    "yadgar_surrealdb_pool_active",
    "yadgar_surrealdb_query_duration_ms",
    "yadgar_tool_pool_inflight",
    "yadgar_tool_pool_max",
    "yadgar_tool_pool_saturated",
    "yadgar_tool_token_estimate_total",
    "yadgar_viz_api_graph_duration_ms",
    "yadgar_viz_dbsize_sample_duration_ms",
    "yadgar_viz_sse_clients",
    "yadgar_wiki_add_rejected_total",
    "yadgar_wiki_embedding_compute_failed_total",
    "yadgar_wiki_query_duration_ms",
    "yadgar_wiki_query_stage_ms",
    "yadgar_write_time_contradiction_total",
    "yadgar_writegate_outcome",
    "yadgar_writes_with_enforcement_relaxed",
)


def __getattr__(name: str):
    if name not in _EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    import importlib  # noqa: PLC0415 — lazy by design (PEP-562 shim)

    return getattr(importlib.import_module(_TARGET), name)


def __dir__() -> list[str]:
    return list(globals()) + list(_EXPORTS)
