"""Wiki policy resolver — maps page_type to routing behaviour.

Car A of #83 (repo-wiki page-type). The repo_wiki page_type itself was
decommissioned (#33/ADR-0162, superseded by code_graph); this resolver
mechanism remains in use by other page types (e.g. agent_prompt).

Design rationale
----------------
Each ``page_type`` has a set of pipeline knobs that control how writes,
retrievals, and gate-checks behave.  Keeping these knobs in CODE (keyed by
``page_type``) rather than per-row data gives:

- A single source of truth for all routing decisions.
- Safe extensibility: adding a new ``page_type`` means adding one entry here.
- Security: ``page_type`` is schema-validated at the write seam (Car B), so
  routing is safe.  It remains NON-canonical for security decisions (e.g.
  branch scoping, ownership) per ADR §0.6 — this module is for BEHAVIOUR
  routing only.

Knob axes
---------
gate_mode
    ``"similarity"`` — default content-similarity gate (cosine threshold).
    ``"identity"``   — slug+schema gate; skip content-similarity entirely.
                        Was used for structural pages (repo_wiki, decommissioned
                        #33) where two thin ``logging.py`` modules from
                        different projects are NOT duplicates despite high
                        cosine similarity.

recall_disposition
    ``"include"``    — pages appear in normal fanout recall (default).
    ``"exclude"``    — pages dropped from SEARCH results (unified-recall fanout
                        AND ``wiki_query``, task 0134) unless the caller opted
                        in by tag — see ``is_recall_visible``. Always reachable
                        by exact key: ``wiki_read`` / ``wiki_get`` /
                        ``wiki_list`` never apply the filter.
    ``"downweight"`` — pages appear in normal fanout recall BUT their ranking
                        score is multiplied by ``RECALL_DOWNWEIGHT_FACTOR``
                        (a value in (0, 1) — default 0.5) at the scoring
                        stage. A downweighted page is still recall-visible
                        (``is_recall_visible`` returns True — exclusion still
                        drops only ``"exclude"``) but sinks below
                        ``"include"`` pages of comparable relevance. Used for
                        ``task_list`` pages (D22: task → downweight); the
                        penalty is applied via ``downweight_multiplier`` at
                        both the unified-recall fusion stage and the legacy
                        ``wiki_query`` search stage.

dir_scope
    ``"strict"``     — gate and retrieval scoped to ``directory_context``.
    ``"global"``     — no directory scoping (e.g. cross-project knowledge).

merge
    ``"allow"``      — LLM-merge allowed on content conflict (default, #19).
    ``"never"``      — upsert / overwrite only; LLM must not touch content.
                        Stub for future #19 guard.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass

from yadgar._shared.observability.observe import observe
from yadgar._shared.wiki.wiki_meta import (
    PAGE_TYPE_AGENT_DISCIPLINE,
    PAGE_TYPE_AGENT_INDEX,
    PAGE_TYPE_AGENT_PATTERN,
    PAGE_TYPE_AGENT_PROMPT_LEGACY,
    PAGE_TYPE_TASK_LIST,
)

# Valid mutability values — the closed set every writer + reader agrees on.
MUTABILITY_FREE = "free"
MUTABILITY_LOCKED = "locked"
MUTABILITY_DERIVED = "derived"
_VALID_MUTABILITY: frozenset[str] = frozenset(
    {MUTABILITY_FREE, MUTABILITY_LOCKED, MUTABILITY_DERIVED}
)

# Public alias of the closed set — ``WikiStore.set_mutability_by_slug`` and
# ``wiki_set_mutability`` validate incoming ``value`` against this rather than
# the private frozenset so the import surface is uniform.
MUTABILITY_VALUES: frozenset[str] = _VALID_MUTABILITY


# Car J (0047 §7 D26): per-type mutability defaults. The policy axis is
# orthogonal to recall_disposition/gate_mode — it gates WRITES at the storage
# chokepoint (``_WikiMixin.update_wiki_page``), not search-time recall.
#
# - adr / adr_superseded → locked: decisions are immutable, the supersede
#   retype (Car G) is the SOLE sanctioned mutator.
# - task / agent_prompt family → free: operational knowledge.
# - wiki_rollup → derived: regenerated by Car K's nightly sweep, not
#   hand-edited.
# - everything else → free (caught by ``get_effective_mutability``'s fallback).
MUTABILITY_BY_TYPE: dict[str, str] = {
    "adr": MUTABILITY_LOCKED,
    "adr_superseded": MUTABILITY_LOCKED,
    "task": MUTABILITY_FREE,
    PAGE_TYPE_AGENT_PROMPT_LEGACY: MUTABILITY_FREE,
    PAGE_TYPE_AGENT_PATTERN: MUTABILITY_FREE,
    PAGE_TYPE_AGENT_DISCIPLINE: MUTABILITY_FREE,
    PAGE_TYPE_AGENT_INDEX: MUTABILITY_FREE,
    "wiki_rollup": MUTABILITY_DERIVED,
}


@dataclass(frozen=True)
class WikiPolicy:
    """Immutable routing policy for a wiki page_type.

    Field order: gate_mode, recall_disposition, dir_scope, merge, storage_scope,
    opt_in_tag. Positional construction is intentional — keep field order
    stable. New fields MUST be appended with defaults so existing 4–6-arg
    positional callers (tests) keep working without changes.
    """

    gate_mode: str
    """``"similarity"`` or ``"identity"``."""

    recall_disposition: str
    """``"include"``, ``"exclude"``, or ``"downweight"``."""

    dir_scope: str
    """``"strict"`` or ``"global"``."""

    merge: str
    """``"allow"`` or ``"never"``."""

    storage_scope: str = "project"
    """``"project"`` — stamped with caller's directory_context (default).
    ``"global"`` — directory_context is overridden to ``"global"`` at write time,
    regardless of what the caller supplied. Used for cross-project shared pages
    (e.g. agent-prompt library) so every project can recall them.

    C2 (#83): enforcement lives in ``WikiStore.add`` — the single write chokepoint
    used by both agent_prompt_save and wiki_add's replay path.
    """

    opt_in_tag: str | None = None
    """Car C1 (0047): per-type opt-in key for the recall exclusion gate.

    ``None`` — the type is excluded UNCONDITIONALLY: no tag the caller passes
    unlocks it. ``agent_index`` (the TOC) uses this — it must never be
    recall-visible (§1.4), and Car I later deletes the TOC page entirely.

    A string value — the ONE tag that unlocks the type when present in the
    caller's ``opt_in_tags``. The page's own ``tags`` field is NOT consulted by
    the exclusion gate; only the TYPE's declared key (ADR-0209 — page_type is
    the policy lever). ``agent_pattern``, ``agent_discipline``, and legacy
    ``agent_prompt`` declare ``"agent-prompt"`` (the documented
    ``recall(tags=["agent-prompt"])`` lookup).
    """

    mutability: str = MUTABILITY_FREE
    """Car J (0047 §7 D25/D26): write-side mutability axis (field #6).

    Values: ``"free"`` | ``"locked"`` | ``"derived"``. The TYPE-level default
    lives in ``MUTABILITY_BY_TYPE``; a per-page ``mutability_override`` on the
    wiki_page row wins over the type default. Enforcement happens at the
    STORAGE chokepoint (``_WikiMixin.update_wiki_page`` + insert/delete for
    symmetry), not at the policy surface — this field is a resolver lever,
    not the enforcement point.

    - ``"free"`` — no enforcement; agent/tool writes allowed.
    - ``"locked"`` — block agent/tool writes; sanctioned server-side
      transitions (Car G supersede retype) pass.
    - ``"derived"`` — block all writes (regenerated, not hand-edited);
      sanctioned transitions pass (Car K nightly sweep deletes + recreates).

    Field appended with a default so existing 4–6-arg positional callers
    (tests across the corpus) keep constructing without error.
    """


# ── Policy registry ──────────────────────────────────────────────────────────

DEFAULT_POLICY = WikiPolicy(
    gate_mode="similarity",
    recall_disposition="include",
    dir_scope="strict",
    merge="allow",
    storage_scope="project",
)
"""Fallback policy for all page types not explicitly listed."""

_AGENT_LIBRARY_POLICY = WikiPolicy(
    gate_mode="identity",
    recall_disposition="exclude",
    dir_scope="strict",
    merge="allow",
    storage_scope="global",
    opt_in_tag="agent-prompt",
    mutability=MUTABILITY_FREE,
)
"""Shared routing for the three agent-prompt-library page types
(``agent_pattern``, ``agent_discipline``, legacy ``agent_prompt``).

ADR-0209 splits the TYPE, not the routing: all library pages stay excluded from
search fanout (they are dispatch scaffolding, not knowledge) and global-scoped
(ADR-0159 — the library is a cross-project shared resource, and a caller-dir
stamp made it invisible from every other project). One shared instance so the
three entries below cannot drift apart silently.

Car C1 (0047): ``opt_in_tag="agent-prompt"`` is the per-type opt-in key — the
documented ``recall(tags=["agent-prompt"])`` lookup reaches these types. The
TOC is SPLIT OFF into ``_AGENT_INDEX_POLICY`` below — it must never be
recall-visible, so its opt_in_tag is None (unconditional exclusion).

Car C3 (0047 §7 D21): ``gate_mode="identity"`` — library pages share
structural prose (all of them are dispatch scaffolding of the same shape), so
the content-similarity gate false-positives on every write. The slug IS the
identity for these types, so the identity gate is a pass-through and the
upsert=False slug-collision check at ``WikiStore.add`` handles real
collisions. (Agent-prompt writes today bypass the drainer gate entirely via
``admin_exec/wiki.py`` → ``wiki.add()`` direct call; this change is
policy-consistent for any future drainer path.)
"""

# Car C1 (0047): split off from _AGENT_LIBRARY_POLICY so the TOC can declare
# ``opt_in_tag=None`` (unconditional exclusion). The TOC carried the library
# tag pre-C1 and surfaced on every ``recall(tags=["agent-prompt"])`` lookup —
# §1.4 documents this as a defect (the tag-override defeats exclusion).
_AGENT_INDEX_POLICY = WikiPolicy(
    gate_mode="similarity",
    recall_disposition="exclude",
    dir_scope="strict",
    merge="allow",
    storage_scope="global",
    opt_in_tag=None,
    mutability=MUTABILITY_FREE,
)

# Car C3 (0047 §7 D21): deterministic-slug canonical page types get the
# identity gate. ADR/task-list pages share structural prose (the canonical
# writers are all generating structurally near-identical content), so the
# content-similarity gate false-positives on every write. The slug IS the
# identity for these types — a re-write of the same slug is an UPDATE, not a
# duplicate. The upsert=False slug-collision check at ``WikiStore.add``
# handles real collisions; the identity gate does not duplicate it. This
# replaces the ``force=True`` / ``replace_slug`` bypasses the canonical
# writers used pre-C3. Per Car C3 plan §3:
#   - recall_disposition: preserve DEFAULT_POLICY value ("include")
#   - merge: preserve DEFAULT_POLICY value ("allow"); D26's "locked" mutability
#     is enforced at storage/wiki.py:215, not at the policy merge field, so
#     merge="never" would silently change wiki-merge behavior beyond the gate.
#   - storage_scope: preserve DEFAULT_POLICY value ("project") — task_list
#     and adr are project-scoped, not cross-project shared.
_ADR_POLICY = WikiPolicy(
    gate_mode="identity",
    recall_disposition="include",
    dir_scope="strict",
    merge="allow",
    storage_scope="project",
    mutability=MUTABILITY_LOCKED,
)

POLICY_BY_TYPE: dict[str, WikiPolicy] = {
    # Pre-ADR-0209 type. Rows on an install that has not run migration 028 still
    # carry it, so the entry must stay until that migration is universal.
    PAGE_TYPE_AGENT_PROMPT_LEGACY: _AGENT_LIBRARY_POLICY,
    PAGE_TYPE_AGENT_PATTERN: _AGENT_LIBRARY_POLICY,
    PAGE_TYPE_AGENT_DISCIPLINE: _AGENT_LIBRARY_POLICY,
    # The TOC index. Registered HERE ONLY (no wiki_page_types.yaml entry) —
    # task 0134: a null page_type fell through to DEFAULT_POLICY include, which
    # made the index recall-visible. Car C1 (0047): split off the shared
    # library policy so opt_in_tag=None makes it unconditional exclusion —
    # closing the §1.4 leak where the TOC surfaced on every targeted prompt
    # lookup. See PAGE_TYPE_AGENT_INDEX's docstring for why it gets no lint
    # schema.
    PAGE_TYPE_AGENT_INDEX: _AGENT_INDEX_POLICY,
    # Car C2 (0047 §7 3b): task_list → downweight (D22). The task list stays
    # recall-visible (the user may legitimately ask "what tasks are open?")
    # but sinks below knowledge pages of comparable relevance. The penalty
    # is applied via `downweight_multiplier` at the scoring stage (fusion +
    # wiki_query), NOT at the visibility filter.
    #
    # Car C3 (0047 §7 D21): task_list → identity gate (replacing
    # gate_mode="similarity" from C2). The downweight disposition is
    # orthogonal — the gate decides pass/reject, the disposition decides
    # recall visibility + ranking penalty. Both coexist. The C2 entry's
    # inline WikiPolicy is collapsed onto the shared ``_TASK_LIST_POLICY``
    # above so task_list routing lives in one place.
    PAGE_TYPE_TASK_LIST: WikiPolicy(
        gate_mode="identity",
        recall_disposition="downweight",
        dir_scope="strict",
        merge="allow",
        storage_scope="project",
    ),
    # Car C3 (0047 §7 D21): adr canonical pages get the identity gate.
    # ``_canonical_adr_payload`` (called from ``adr_add``) used to set
    # ``force=True`` to bypass the similarity gate; that bypass is now
    # unnecessary because adr's gate_mode is identity. See adr_render.py
    # for the deleted ``force=True`` line.
    "adr": _ADR_POLICY,
}
"""Explicit overrides keyed by page_type string.

(repo_wiki's ``identity``/``exclude``/``never`` override was removed when the
repo_wiki generator was decommissioned — #33/ADR-0162, superseded by
code_graph's injected-memory-block model which stores no wiki pages at all.

Car C3 (0047 §7 D21): the identity gate path is restored for
deterministic-slug page types — ``adr`` (added), ``task_list`` (gate_mode
flipped from similarity), and the agent-prompt library
(``agent_pattern``/``agent_discipline``/legacy ``agent_prompt`` — gate_mode
flipped via ``_AGENT_LIBRARY_POLICY``). The slug IS the identity for these
types: a re-write of the same slug is an update, not a duplicate.)
"""


# ── Resolver ─────────────────────────────────────────────────────────────────


@observe(tier="stage")
def get_policy(page_type: str | None) -> WikiPolicy:
    """Return the ``WikiPolicy`` for *page_type*, or ``DEFAULT_POLICY``.

    Args:
        page_type: The ``page_type`` field from a wiki page.  ``None`` and
            any unrecognised string both return ``DEFAULT_POLICY``.

    Returns:
        A frozen ``WikiPolicy`` instance. Each registered policy declares its
        own ``mutability`` field at construction time (see ``_ADR_POLICY``
        / ``_AGENT_LIBRARY_POLICY`` / ``_AGENT_INDEX_POLICY`` above); the
        default policy is ``"free"`` (set by the field default). Per-page
        ``mutability_override`` is NOT consulted here — that's a row-level
        concern handled by ``get_effective_mutability``. Storage-layer
        enforcement uses ``get_effective_mutability`` so the row override
        always wins.
    """
    if page_type is None:
        return DEFAULT_POLICY
    return POLICY_BY_TYPE.get(page_type, DEFAULT_POLICY)


@observe(tier="hot")
def is_recall_visible(page: dict, opt_in_tags: Sequence[str] | None = None) -> bool:
    """Return whether *page* may appear in SEARCH results.

    The single rule shared by the unified-recall wiki provider and
    ``wiki_query`` (task 0134 fixed both call sites diverging).

    Car C1 (0047): the opt-in is PER TYPE — an excluded page survives only when
    the caller's ``opt_in_tags`` include its page_type's declared
    ``opt_in_tag`` (a ``WikiPolicy`` field). The page's own ``tags`` field is
    NO LONGER read for the exclusion gate (page tags still matter upstream for
    the SQL pre-filter / HNSW ranking path — unaffected by this car). A type
    with ``opt_in_tag=None`` is excluded unconditionally — no tag unlocks it.
    ``agent_index`` (the TOC) declares ``None``; ``agent_pattern``,
    ``agent_discipline``, and legacy ``agent_prompt`` declare
    ``"agent-prompt"``.

    This narrows the 0134 rule (per-page tag intersection): task 0134 fixed the
    blanket kill-switch, but any-tag intersection still let an excluded page
    survive on an unrelated caller tag. C1 tightens it once more — the unlock
    signal is the TYPE's declared key, not the page's own tags.

    Args:
        page: A wiki page dict; reads ``page_type`` only.
        opt_in_tags: Tags the caller explicitly asked for, if any.

    Returns:
        True when the page may be returned by a search path.
    """
    policy = get_policy(page.get("page_type"))
    if policy.recall_disposition != "exclude":
        return True
    if not opt_in_tags or policy.opt_in_tag is None:
        return False
    return policy.opt_in_tag in set(opt_in_tags)


@observe(tier="hot")
def downweight_multiplier(page: dict, factor: float) -> float:
    """Return the ranking-score multiplier for *page*.

    Car C2 (0047 §7 3b): a downweighted page passes ``is_recall_visible``
    (visibility is unchanged — exclusion still drops only ``"exclude"``) but
    its ranking score is multiplied by *factor* so it sinks below
    ``"include"`` pages of comparable relevance. Returns *factor* (a value
    in (0, 1)) when the page's ``page_type`` resolves to
    ``recall_disposition="downweight"``; ``1.0`` otherwise.

    Single source of truth for the penalty — called from
    ``yadgar.backend.retrieval.providers.fusion`` (unified recall) and
    ``yadgar.core.server.tools.wiki.wiki_query`` (the legacy search tool).
    The *factor* is passed in (not read from settings inside the helper) so
    the helper is testable without a Settings instance and stays in
    ``_shared`` (no config import — ``_shared`` policy stays config-agnostic).

    An excluded page (``recall_disposition="exclude"``) returns ``1.0``
    here on purpose — exclusion is enforced earlier in the pipeline
    (``is_recall_visible`` drops ``exclude`` rows before scoring) so a
    non-1.0 return value can never leak penalty to an excluded row. The
    helper is composable: callers can apply it unconditionally without
    second-guessing the disposition.
    """
    if get_policy(page.get("page_type")).recall_disposition == "downweight":
        return float(factor)
    return 1.0


# ── Car J (0047 §7 D25/D26) — mutability resolver ─────────────────────────────


@observe(tier="hot")
def get_effective_mutability(
    page: dict,
    override: str | None = None,
) -> str:
    """Return the effective mutability for *page*.

    Single source of truth for mutability resolution — called from the
    storage write chokepoint (``_WikiMixin.update_wiki_page``,
    ``insert_wiki_page``, ``delete_wiki_page``) and the
    ``wiki_set_mutability`` tool. Centralised here so storage + tool layer
    share one function (Car J §4.7 refactor).

    Resolution order (later wins):

    1. Per-type default (``MUTABILITY_BY_TYPE[page_type]``) — falls back to
       ``"free"`` for unknown / ``None`` page types.
    2. Per-page override from the wiki_page row's ``mutability_override``
       column — read from *page* dict if present.
    3. Explicit *override* kwarg — lets callers that have already resolved
       the override (e.g. ``WikiStore.set_mutability_by_slug`` passing the
       new value, ``_WikiMixin.update_wiki_page`` reading the row) bypass
       the dict read.

    Returns one of ``"free"``, ``"locked"``, ``"derived"``.
    """
    # Step 1: per-type default
    page_type = page.get("page_type")
    default = MUTABILITY_BY_TYPE.get(page_type or "", MUTABILITY_FREE)

    # Step 2: per-page override from the row dict (read once).
    # ``page.get("mutability_override")`` returns None both when the key is
    # absent (pre-migration rows) and when it is stored as a null — both
    # fall through to the per-type default. Idempotent under migration 030.
    row_override = page.get("mutability_override")

    # Step 3: explicit kwarg wins (None means "no kwarg override")
    if override is not None:
        return override
    if row_override is not None:
        return row_override
    return default


# Re-export for tests + callers that want a closed-set check without
# importing the private frozenset.
__all__ = [  # noqa: F401 — module-level re-export
    "DEFAULT_POLICY",
    "MUTABILITY_BY_TYPE",
    "MUTABILITY_DERIVED",
    "MUTABILITY_FREE",
    "MUTABILITY_LOCKED",
    "MUTABILITY_VALUES",
    "POLICY_BY_TYPE",
    "WikiPolicy",
    "downweight_multiplier",
    "get_effective_mutability",
    "get_policy",
    "is_recall_visible",
]
