"""Tests for yadgar/curation/prune_passes.py — memify prune logic.

Wave 2 coverage: yadgar/curation/prune_passes.py (109 stmts, 6.4% pre-wave).
Strategy: mock StorageEngine and Settings at the module boundary.
_memify_prune has 6 passes — each gets its own test group.
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from unittest.mock import MagicMock, patch

from yadgar.backend.curation.prune_passes import _memify_prune

# ---------------------------------------------------------------------------
# Fixtures / helpers
# ---------------------------------------------------------------------------


def _settings(
    cold_threshold=0.05,
    auto_generated_max_age=30,
    auto_abstracted_max_age=30,
    dream_max_age=14,
    action_stream_max_age=90,
):
    s = MagicMock()
    s.COLD_THRESHOLD = cold_threshold
    s.AUTO_GENERATED_MEMORY_MAX_AGE_DAYS = auto_generated_max_age
    s.AUTO_ABSTRACTED_MEMORY_MAX_AGE_DAYS = auto_abstracted_max_age
    s.DREAM_INSIGHT_MAX_AGE_DAYS = dream_max_age
    s.ACTION_STREAM_MAX_AGE_DAYS = action_stream_max_age
    return s


def _mem(
    mid,
    tags,
    heat=0.5,
    access_count=0,
    is_protected=False,
    created_days_ago=0,
    last_accessed_days_ago=None,  # default: mirrors created_at (never recalled since creation)
    content="memory content",
    **kw,
):
    """Build a minimal memory dict.  Extra fields (e.g. confidence) via **kw."""
    created = (datetime.now(UTC) - timedelta(days=created_days_ago)).isoformat()
    if last_accessed_days_ago is None:
        last_accessed = created
    else:
        last_accessed = (datetime.now(UTC) - timedelta(days=last_accessed_days_ago)).isoformat()
    return {
        "id": mid,
        "tags": tags,
        "heat": heat,
        "confidence": kw.get("confidence", 1.0),
        "access_count": access_count,
        "is_protected": is_protected,
        "created_at": created,
        "last_accessed": last_accessed,
        "content": content,
    }


def _storage(*memories):
    s = MagicMock()
    s.get_memories_by_heat.return_value = list(memories)
    return s


# ---------------------------------------------------------------------------
# Pass 1: action-stream cold/low-confidence/unaccessed
# ---------------------------------------------------------------------------


class TestPass1ActionStream:
    def test_cold_low_confidence_unaccessed_deleted(self):
        mem = _mem(1, ["_action_stream"], heat=0.005, confidence=0.1, access_count=0)
        storage = _storage(mem)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(), stats)
        storage.delete_memory.assert_called_once_with(1)
        assert stats["pruned"] == 1

    def test_protected_skipped(self):
        mem = _mem(
            2, ["_action_stream"], heat=0.005, confidence=0.1, access_count=0, is_protected=True
        )
        storage = _storage(mem)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(), stats)
        storage.delete_memory.assert_not_called()

    def test_warm_heat_not_pruned(self):
        mem = _mem(3, ["_action_stream"], heat=0.5, confidence=0.1, access_count=0)
        storage = _storage(mem)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(), stats)
        storage.delete_memory.assert_not_called()

    def test_high_confidence_not_pruned(self):
        mem = _mem(4, ["_action_stream"], heat=0.005, confidence=0.8, access_count=0)
        storage = _storage(mem)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(), stats)
        storage.delete_memory.assert_not_called()

    def test_accessed_not_pruned(self):
        mem = _mem(5, ["_action_stream"], heat=0.005, confidence=0.1, access_count=1)
        storage = _storage(mem)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(), stats)
        storage.delete_memory.assert_not_called()

    def test_tags_as_json_string_parsed(self):
        """Tags stored as JSON string should still work."""
        import json

        mem = _mem(6, ["_action_stream"], heat=0.005, confidence=0.1, access_count=0)
        mem["tags"] = json.dumps(["_action_stream"])
        storage = _storage(mem)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(), stats)
        storage.delete_memory.assert_called_once_with(6)


# ---------------------------------------------------------------------------
# Pass 2: auto-generated cold unaccessed old memories
# ---------------------------------------------------------------------------


class TestPass2AutoGenerated:
    def test_cold_old_unaccessed_deleted(self):
        mem = _mem(10, ["auto-generated"], heat=0.01, access_count=0, created_days_ago=60)
        storage = _storage(mem)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(cold_threshold=0.05, auto_generated_max_age=30), stats)
        storage.delete_memory.assert_called_with(10)

    def test_too_recent_spared(self):
        mem = _mem(11, ["auto-generated"], heat=0.01, access_count=0, created_days_ago=5)
        storage = _storage(mem)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(auto_generated_max_age=30), stats)
        storage.delete_memory.assert_not_called()

    def test_recently_accessed_still_purged(self):
        """Task 386: HEAT is pass 2's recency signal; the timestamp is not.

        This fixture is the reason the deleted branch survived review: it is a
        state the live system cannot produce.  ``boost_memories_access`` is the
        only production writer of ``last_accessed`` and it sets
        ``heat = min(heat + 0.1, 1.0)`` in the SAME statement, so a row read 5
        days ago cannot be at heat=0.01 — it would be >= 0.1, decaying under
        ``COLD_THRESHOLD`` only after ~134 days at ``DECAY_FACTOR=0.9995``, and
        the heat gate above would have spared it long before the timestamp was
        consulted.  The pass now relies on that gate alone.

        RED on the v5.66 code (spared by ``last_accessed``); GREEN once the
        reprieve is gone.
        """
        mem = _mem(
            12,
            ["auto-generated"],
            heat=0.01,  # cold: unreachable in prod alongside a 5d-old access
            access_count=1,
            created_days_ago=60,
            last_accessed_days_ago=5,
        )
        storage = _storage(mem)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(auto_generated_max_age=30), stats)
        storage.delete_memory.assert_called_once_with(12)

    def test_stale_accessed_purged(self):
        """v5.66: old+stale (last_accessed beyond cutoff) -> purged despite access_count>0."""
        mem = _mem(
            15,
            ["auto-generated"],
            heat=0.01,
            access_count=1,
            created_days_ago=60,
            last_accessed_days_ago=45,  # stale: 45d ago, cutoff=30d -> purge
        )
        storage = _storage(mem)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(cold_threshold=0.05, auto_generated_max_age=30), stats)
        storage.delete_memory.assert_called_once_with(15)

    def test_warm_spared(self):
        mem = _mem(13, ["auto-generated"], heat=0.5, access_count=0, created_days_ago=60)
        storage = _storage(mem)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(cold_threshold=0.05, auto_generated_max_age=30), stats)
        storage.delete_memory.assert_not_called()

    def test_disabled_max_age_skips_pass(self):
        mem = _mem(14, ["auto-generated"], heat=0.01, access_count=0, created_days_ago=60)
        storage = _storage(mem)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(auto_generated_max_age=0), stats)
        # Pass disabled; only pass 1 could fire (no _action_stream tag)
        storage.delete_memory.assert_not_called()


# ---------------------------------------------------------------------------
# Pass 3: auto-abstracted age cap (no heat check)
# ---------------------------------------------------------------------------


class TestPass3AutoAbstracted:
    def test_old_unaccessed_deleted(self):
        mem = _mem(20, ["auto-abstracted"], heat=0.5, access_count=0, created_days_ago=60)
        storage = _storage(mem)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(auto_abstracted_max_age=30), stats)
        storage.delete_memory.assert_called_with(20)

    def test_recent_spared(self):
        mem = _mem(21, ["auto-abstracted"], heat=0.5, access_count=0, created_days_ago=5)
        storage = _storage(mem)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(auto_abstracted_max_age=30), stats)
        storage.delete_memory.assert_not_called()

    def test_recently_accessed_still_purged(self):
        """Task 386: the age cap is an AGE cap — recent access is no reprieve.

        RED on the v5.66 code (``last_accessed > cutoff -> continue`` spared
        it); GREEN once pass 3 caps on ``created_at`` alone.  ``recall()``
        bumps ``last_accessed`` on every hit, so a row that keeps matching
        kept renewing its own reprieve — retrieval frequency is not evidence
        of value for a machine-generated abstraction.
        """
        mem = _mem(
            22,
            ["auto-abstracted"],
            heat=0.5,
            access_count=1,
            created_days_ago=60,
            last_accessed_days_ago=5,  # read 5d ago — irrelevant, 60d > 30d cap
        )
        storage = _storage(mem)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(auto_abstracted_max_age=30), stats)
        storage.delete_memory.assert_called_once_with(22)

    def test_stale_accessed_purged(self):
        """v5.66: old+stale (last_accessed beyond cutoff) -> purged despite access_count>0."""
        mem = _mem(
            23,
            ["auto-abstracted"],
            heat=0.5,
            access_count=1,
            created_days_ago=60,
            last_accessed_days_ago=45,  # stale: 45d ago, cutoff=30d -> purge
        )
        storage = _storage(mem)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(auto_abstracted_max_age=30), stats)
        storage.delete_memory.assert_called_once_with(23)


# ---------------------------------------------------------------------------
# Pass 4: dream insight age cap
# ---------------------------------------------------------------------------


class TestPass4DreamInsights:
    def test_old_dream_deleted(self):
        mem = _mem(30, ["dream", "auto-generated"], heat=0.5, access_count=0, created_days_ago=30)
        storage = _storage(mem)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(dream_max_age=14), stats)
        storage.delete_memory.assert_called_with(30)

    def test_recent_dream_spared(self):
        mem = _mem(31, ["dream", "auto-generated"], heat=0.5, created_days_ago=5)
        storage = _storage(mem)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(dream_max_age=14), stats)
        storage.delete_memory.assert_not_called()

    def test_dream_without_auto_generated_spared(self):
        # Needs BOTH "dream" AND "auto-generated" tags
        mem = _mem(32, ["dream"], created_days_ago=30)
        storage = _storage(mem)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(dream_max_age=14), stats)
        storage.delete_memory.assert_not_called()

    def test_protected_dream_spared(self):
        mem = _mem(33, ["dream", "auto-generated"], is_protected=True, created_days_ago=30)
        storage = _storage(mem)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(dream_max_age=14), stats)
        storage.delete_memory.assert_not_called()


# ---------------------------------------------------------------------------
# Pass 5: action-stream age cap
# ---------------------------------------------------------------------------


class TestPass5ActionStreamAgeCap:
    def test_old_unaccessed_deleted(self):
        mem = _mem(
            40, ["_action_stream"], heat=0.4, access_count=0, created_days_ago=180, confidence=0.9
        )
        storage = _storage(mem)
        stats = {"pruned": 0}
        # High confidence prevents pass 1, but pass 5 fires on age+unaccessed
        _memify_prune(storage, _settings(action_stream_max_age=90, cold_threshold=0.05), stats)
        storage.delete_memory.assert_called_with(40)

    def test_recently_accessed_still_purged_by_age_cap(self):
        """Task 386: pass 5 has no heat gate, so the age cap is the only cap.

        heat=0.4 with confidence=0.9 clears pass 1 entirely, and pass 1's own
        gate needs ~300 days to fire — so a reprieve on THIS cap did not defer
        the deletion, it cancelled it.  ``recall()`` writes ``last_accessed``,
        so a summary that kept matching kept renewing its own reprieve. Unlike
        pass 2 there was no heat gate behind it: this one was live at the
        shipped defaults.

        RED on the v5.66 code; GREEN once the reprieve is gone.
        """
        mem = _mem(
            41,
            ["_action_stream"],
            heat=0.4,
            access_count=1,
            created_days_ago=180,
            last_accessed_days_ago=10,
            confidence=0.9,
        )
        storage = _storage(mem)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(action_stream_max_age=90, cold_threshold=0.05), stats)
        storage.delete_memory.assert_called_once_with(41)

    def test_stale_accessed_purged_age_cap(self):
        """v5.66: old+stale action-stream -> purged despite access_count>0."""
        mem = _mem(
            43,
            ["_action_stream"],
            heat=0.4,
            access_count=2,
            created_days_ago=180,
            last_accessed_days_ago=120,  # stale: 120d ago, cutoff=90d -> purge
            confidence=0.9,
        )
        storage = _storage(mem)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(action_stream_max_age=90, cold_threshold=0.05), stats)
        storage.delete_memory.assert_called_once_with(43)

    def test_recent_spared(self):
        mem = _mem(
            42, ["_action_stream"], heat=0.4, access_count=0, created_days_ago=10, confidence=0.9
        )
        storage = _storage(mem)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(action_stream_max_age=90), stats)
        storage.delete_memory.assert_not_called()


# ---------------------------------------------------------------------------
# Pass 6: degenerate auto-abstracted
# ---------------------------------------------------------------------------


class TestPass6Degenerate:
    def test_degenerate_deleted(self):
        mem = _mem(
            50,
            ["auto-abstracted"],
            access_count=0,
            content="Recurring pattern across 3 observations: frequently modified together",
        )
        storage = _storage(mem)
        stats = {"pruned": 0}

        with patch(
            "yadgar.backend.curation.prune_passes._is_degenerate_auto_abstracted",
            return_value=True,
        ):
            _memify_prune(storage, _settings(), stats)

        storage.delete_memory.assert_called_with(50)

    def test_non_degenerate_spared(self):
        mem = _mem(51, ["auto-abstracted"], access_count=0, content="Real semantic cluster content")
        storage = _storage(mem)
        stats = {"pruned": 0}

        with patch(
            "yadgar.backend.curation.prune_passes._is_degenerate_auto_abstracted",
            return_value=False,
        ):
            _memify_prune(storage, _settings(), stats)

        storage.delete_memory.assert_not_called()

    def test_accessed_degenerate_still_purged(self):
        """v5.66: degenerate content is never meaningful; access_count no longer protects it."""
        mem = _mem(
            52,
            ["auto-abstracted"],
            access_count=2,
            content="Recurring pattern across 3 observations: frequently modified together",
        )
        storage = _storage(mem)
        stats = {"pruned": 0}

        with patch(
            "yadgar.backend.curation.prune_passes._is_degenerate_auto_abstracted",
            return_value=True,
        ):
            _memify_prune(storage, _settings(), stats)

        storage.delete_memory.assert_called_once_with(52)

    def test_protected_spared(self):
        mem = _mem(
            53,
            ["auto-abstracted"],
            access_count=0,
            is_protected=True,
            content="Recurring pattern across 3 observations: frequently modified together",
        )
        storage = _storage(mem)
        stats = {"pruned": 0}

        with patch(
            "yadgar.backend.curation.prune_passes._is_degenerate_auto_abstracted",
            return_value=True,
        ):
            _memify_prune(storage, _settings(), stats)

        storage.delete_memory.assert_not_called()


# ---------------------------------------------------------------------------
# Stats accumulation
# ---------------------------------------------------------------------------


class TestStatsAccumulation:
    def test_multiple_pruned_increments_stats(self):
        mems = [
            _mem(i, ["_action_stream"], heat=0.005, confidence=0.1, access_count=0)
            for i in range(5)
        ]
        storage = _storage(*mems)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(), stats)
        assert stats["pruned"] == 5

    def test_no_prunable_memories_leaves_stats_unchanged(self):
        mem = _mem(99, ["user-created"], heat=1.0)
        storage = _storage(mem)
        stats = {"pruned": 0}
        _memify_prune(storage, _settings(), stats)
        assert stats["pruned"] == 0
