#!/usr/bin/env python3
"""Guard: inline `# noqa: XXXX` comments must target rules that are actually
in the resolved pyproject `[tool.ruff.lint] select` set, and must state a rule.

WHY THIS EXISTS (Car C2 / task 313, bug-bag-2 train 2026-08-23)
--------------------------------------------------------------
The sibling ``check_ruff_ignores_liveness.py`` (car 7, 2026-08-13) only
covers ``pyproject.toml`` ``[tool.ruff.lint.per-file-ignores]`` — the file-
level table. Inline ``# noqa: XXXX`` suppressions on individual lines were
never gated, so 309 ``# noqa: BLE001`` sites in this repo were silently
suppressing a rule that ruff does not run (BLE001 is not in pyproject
``select``). Every one of those suppressions hides the NEXT violation of
the named rule in that file with no signal — the same silent-suppression
class the per-file-ignores gate was built to catch, one rung deeper.

Two failure classes caught here:

  (a) INERT-RULE — ``# noqa: XXXX`` where ``XXXX`` is not in the resolved
      ``select`` (the 309 BLE001 sites). The named rule is dead, so the
      suppression silences nothing — but a developer who later adds the
      rule to ``select`` would suddenly find it suppressed with no audit
      trail.

  (b) BARE / EMPTY — ``# noqa`` or ``# noqa:`` with no rule code stated
      (9 sites in the repo, one of them bare ``# noqa`` with nothing
      after). A blanket suppression is too coarse to audit; the gate
      requires a named rule.

A third class (VACUOUS — noqa: XXXX where XXXX IS in select but the line
below doesn't trigger XXXX) is left to ``check_ruff_ignores_liveness``'s
spirit and is intentionally NOT checked here: it would require running
ruff per-site, which is O(lines) subprocesses for marginal signal — the
named-rule match against ``select`` already catches the silent-suppression
class the audit found.

ONE-SUBPROCESS DESIGN
---------------------
The script does NOT shell out to ruff for every site. The ``select`` set
is read once from ``pyproject.toml``. The file scan is a single Python
pass over ``yadgar/`` (regex-based, fast).

CEILING
-------
Like the sibling, this is a guard against silent drift, not a ban on
suppressions. A correctly-named, correctly-targeting ``# noqa: C901`` on
a single cyclomatic-complexity line will pass. The audit found only the
INERT and BARE classes in scope.

Exit codes:
  0  no inert-rule or bare noqa sites in yadgar/
  1  one or more sites flagged
"""

from __future__ import annotations

import re
import sys
import tomllib
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
_PYPROJECT = _REPO_ROOT / "pyproject.toml"

# Recognise both single-code (hash + ``noqa:`` + code, e.g. E402) and
# comma-separated codes (e.g. E402 + F401), AND bare (hash + ``noqa``
# with no colon) / empty (hash + ``noqa:`` with nothing or whitespace
# after) — the BARE class.
#
# Anchored on the trailing-position pattern: ruff only suppresses the LINE
# the comment sits on, so we only care about a noqa-comment that is the
# LAST thing on its line.
#
# Capture groups:
#   1: raw code-string (possibly empty) — checked for INERT-RULE / BARE
#      Empty/whitespace-only → BARE.
#      ``None`` (no colon) → also BARE.
_NOQA_RE = re.compile(r"^[^#\n]*#\s*noqa(?::\s*([A-Z0-9,\s]*?))?\s*$")

# A valid ruff code shape: 1-3 uppercase letters followed by 3-4 digits.
# Matches: A002, B017 (flake8-pytest-style), E402 (pycodestyle),
# PLC0414 (pylint 4-digit), BLE001 (flake8-blind-except).
_CODE_RE = re.compile(r"^[A-Z]{1,3}\d{3,4}$")

# Baseline allowlist — pre-C2 inert noqa sites the gate accepts during
# the cleanup window. Format: ``<relpath>:<lineno>:<CODE>`` per line.
# Generated by car C2 (2026-08-23, task 313) from a one-time scan.
# Cleanup owner: future car. The gate ships WITH this baseline so the
# pre-commit hook can fire on NEW inert sites without blocking the
# existing 953.
_BASELINE_FILENAME = "baseline_noqa_inert.txt"


def load_baseline(repo_root: Path) -> set[tuple[str, int, str]]:
    """Load the inert-noqa baseline, or empty set if missing.

    Format per line: ``<relpath>:<lineno>:<CODE>``. Lines that don't parse
    are silently ignored — a corrupted baseline should not block CI.
    The path is matched RELATIVE to repo_root (same as the scan).

    A missing baseline file is NOT an error: the gate operates in
    "report-only" mode, surfacing every inert site without an allowlist.
    This is the desired behaviour for a fresh checkout that hasn't
    initialised the baseline yet.
    """
    baseline_path = repo_root / "scripts" / _BASELINE_FILENAME
    if not baseline_path.is_file():
        return set()
    out: set[tuple[str, int, str]] = set()
    for line in baseline_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        try:
            path, lineno_s, code = line.rsplit(":", 2)
            lineno = int(lineno_s)
        except ValueError:
            continue
        out.add((path.strip(), lineno, code.strip()))
    return out


def load_select(pyproject_path: Path) -> set[str] | None:
    """Return the resolved ``select`` set, or None if pyproject is missing.

    Reads BOTH top-level ``select`` AND ``extend-select`` — both contribute
    to which rules ruff runs.

    None is the missing-config sentinel: callers must pass it through (a
    repo with no pyproject has nothing to gate against, so this gate is
    a no-op there).
    """
    if not pyproject_path.is_file():
        return None
    data = tomllib.loads(pyproject_path.read_text(encoding="utf-8"))
    ruff = data.get("tool", {}).get("ruff", {})
    lint = ruff.get("lint", {})
    raw = set(lint.get("select", []) or [])
    raw.update(lint.get("extend-select", []) or [])
    return {code.strip() for code in raw if code and isinstance(code, str)}


def _select_expands(select: set[str]) -> set[str]:
    """Expand ``select`` to include all rule shapes any family would match.

    Given ``select = {"E", "W", "BLE", "C901", "PLR0913"}``, this returns
    the original set PLUS every legal rule code that begins with a family
    prefix in the set. Used by the gate to decide if ``# noqa: E402`` is
    live when ``select = {"E"}`` — yes, because E402 matches the E-family.

    This deliberately over-generates — there is no rule ``E0001`` today,
    but the gate should still accept a hypothetical ``# noqa: E0001``
    against ``select = {"E"}`` rather than flag it inert, because ruff
    itself would accept that suppression. False negatives at the INERT
    boundary are worse than false positives.
    """
    expanded = set(select)
    families = {code for code in select if code.rstrip("0123456789") == code}
    if not families:
        return expanded
    for prefix in families:
        for n in range(0, 1000):  # 3-digit rules
            expanded.add(f"{prefix}{n:03d}")
        for n in range(0, 10000):  # 4-digit rules
            expanded.add(f"{prefix}{n:04d}")
    return expanded


def _scan_one(
    path: Path,
    select: set[str],
    repo_root: Path,
    baseline: set[tuple[str, int, str]] | None = None,
) -> list[str]:
    """Scan one Python file for INERT-RULE and BARE noqa sites.

    Returns a list of formatted error strings — empty list means clean.
    ``baseline`` is the set of (relpath, lineno, code) triples the gate
    allows through during the cleanup window; pass ``None`` to skip the
    allowlist (every inert site is reported).
    """
    errors: list[str] = []
    try:
        body = path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError):  # fmt: skip
        return errors  # not a text file we can read — skip silently

    try:
        rel = path.relative_to(repo_root).as_posix()
    except ValueError:  # pragma: no cover - defensive
        rel = str(path)
    for lineno, line in enumerate(body.splitlines(), start=1):
        m = _NOQA_RE.match(line)
        if m is None:
            continue  # not a noqa line — skip
        codes_str = (m.group(1) or "").strip()
        if not codes_str:
            # BARE / EMPTY class — must be flagged. Never allowlisted: a
            # blanket suppression with no rule is ALWAYS a defect.
            errors.append(
                f"BARE: {rel}:{lineno}: bare `# noqa` (no rule code) — "
                "specify the rule you are suppressing, or ruff treats it as "
                "a blanket suppression that no lint pass can audit."
            )
            continue
        # Split on comma, validate each code.
        for code in (c.strip() for c in codes_str.split(",")):
            if not code:
                continue
            if not _CODE_RE.match(code):
                # Not a ruff-shaped code (e.g. typo). Flag as inert too —
                # the gate's whole point is "names a rule ruff will run."
                # Not allowlisted: a misspelled rule is ALWAYS a defect.
                errors.append(
                    f"INERT-RULE: {rel}:{lineno}: `# noqa: {code}` names a "
                    "rule that is not a valid ruff code (expected one or two "
                    "uppercase letters + 3-4 digits). Either it is misspelled "
                    "or ruff silently ignores it."
                )
                continue
            if code not in select:
                if baseline is not None and (rel, lineno, code) in baseline:
                    # Pre-C2 inert site — cleanup window allows it through.
                    # The baseline itself is the cleanup backlog; the gate
                    # does NOT shrink it (cleanup is a manual car-by-car
                    # effort tracked in `scripts/baseline_noqa_inert.txt`).
                    continue
                errors.append(
                    f"INERT-RULE: {rel}:{lineno}: `# noqa: {code}` suppresses "
                    f"a rule ruff does not run for this project "
                    f"(not in pyproject `[tool.ruff.lint] select`). The "
                    "suppression is a silent no-op today — drop the noqa "
                    "or add the rule to `select` with a stated reason."
                )
    return errors


def check(repo_root: Path | None = None) -> list[str]:
    """Walk yadgar/ for INERT-RULE / BARE noqa sites.

    Returns a list of formatted error strings. Empty list means clean.
    Missing pyproject → empty list (no config to drift against, nothing to gate).
    Missing baseline → all inert sites reported (no allowlist).
    """
    repo_root = repo_root or _REPO_ROOT
    pyproject = repo_root / "pyproject.toml"
    select = load_select(pyproject)
    if select is None:
        # No pyproject → no resolved select → nothing to gate. This is the
        # sentinel the tests pin to ensure the gate doesn't false-positive
        # on a sub-project with its own ruff config (none today, but the
        # contract is future-proof).
        return []
    # Expand families (`select = ["E"]` enables all E-codes) so the INERT
    # check matches ruff's own resolution rules. Without this, every
    # `# noqa: E402` site would be falsely flagged against `select = ["E"]`.
    select_expanded = _select_expands(select)
    # If select is empty (`select = []`), all named rules are inert. The
    # script still scans; every named code becomes an INERT-RULE report.
    baseline = load_baseline(repo_root)
    errors: list[str] = []
    yadgar = repo_root / "yadgar"
    if not yadgar.is_dir():
        return errors
    for path in sorted(yadgar.rglob("*.py")):
        errors.extend(_scan_one(path, select_expanded, repo_root, baseline))
    return errors


def main(argv: list[str] | None = None) -> int:
    del argv  # no CLI args today — kept for parity with sibling check_*.py scripts
    errors = check()
    if errors:
        print("ruff noqa liveness check FAILED:", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        # Total count summary at the end so a 309-line failure is readable.
        print(f"\n  total: {len(errors)} violation(s)", file=sys.stderr)
        return 1
    print("ruff noqa liveness check OK.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
